hassio-addons/addon-tasmoadmin

README.md

This is a PR to correct a minor spelling error

Minor spelling error

---

tasmoadmin/DOCS.md

Add note on OTA over SSL
Lots...

✏ Add note on OTA over SSL

---

tasmoadmin/Dockerfile

Required for image to build.
#99

:arrow_up: Upgrades PHP to 7.3.23

---

LICENSE.md
README.md
tasmoadmin/.README.j2
tasmoadmin/DOCS.md

Happy New Year

---

tasmoadmin/Dockerfile
tasmoadmin/build.json
tasmoadmin/config.json

Upgrades the add-on base image to the 9.x series, upgrading all OS dependencies in the process.

Upgrade add-on base image to 9.1.2

---

tasmoadmin/Dockerfile

:arrow_up: Upgrades php7 to 7.4.15-r0

---

tasmoadmin/Dockerfile

:arrow_up: Upgrades git to 2.30.1-r0

---

tasmoadmin/Dockerfile

⬆️ Upgrades git to 2.30.2-r0

---

tasmoadmin/Dockerfile
tasmoadmin/build.json

Upgrades add-on base image to v9.1.5

⬆️  Upgrades add-on base image to v9.1.5

---

tasmoadmin/Dockerfile
tasmoadmin/build.json

Upgrades add-on base image to v9.1.7

⬆️ Upgrades add-on base image to v9.1.7

---

tasmoadmin/Dockerfile
tasmoadmin/build.json

Upgrades add-on base image to v9.2.0

Upgrades add-on base image to v9.2.0

---

tasmoadmin/translations/en.yaml

Add translation support to the add-on configuration.

Add add-on translation support

---

tasmoadmin/Dockerfile

⬆️ Upgrades php7 to 7.4.19-r0

---

tasmoadmin/Dockerfile
tasmoadmin/build.json

pgrades add-on base image to v9.2.1

⬆️ Upgrades add-on base image to v9.2.1

---

tasmoadmin/Dockerfile
tasmoadmin/build.json

Upgrades add-on base image to v10.0.0

⬆️ Upgrades add-on base image to v10.0.0

---

tasmoadmin/Dockerfile

⬆️ Upgrades php7 to 7.4.21-r0

---

tasmoadmin/Dockerfile

⬆️ Upgrades php7 to 7.4.22-r0

---

tasmoadmin/Dockerfile
tasmoadmin/build.json

Upgrades add-on base image to v10.0.1

⬆️ Upgrades add-on base image to v10.0.1

---

tasmoadmin/Dockerfile

⬆️ Upgrades php7 to 7.4.24-r0

---

tasmoadmin/Dockerfile
tasmoadmin/build.json

Upgrades add-on base image to 10.1.0

⬆️ Upgrades add-on base image to 10.1.0

---

tasmoadmin/Dockerfile

⬆️ Upgrades php7 to 7.4.25-r0

---

tasmoadmin/Dockerfile
tasmoadmin/build.yaml

Upgrades add-on base image to 10.2.2

⬆️ Upgrades add-on base image to 10.2.2

---

LICENSE.md
README.md
tasmoadmin/.README.j2
tasmoadmin/DOCS.md

:fireworks: Updates maintenance/license year to 2022

---

tasmoadmin/Dockerfile
tasmoadmin/build.yaml

Upgrades add-on base image to 11.0.1

⬆️ Upgrades add-on base image to 11.0.1

---

tasmoadmin/Dockerfile

Update to https://github.com/reloxx13/TasmoAdmin/releases/tag/v1.8.0
Resolves #223
Pending merge of #230

⬆️ Upgrades TasmoAdmin to v1.8.0

---

tasmoadmin/Dockerfile
tasmoadmin/build.yaml

Upgrades add-on base image to 11.1.0

⬆️ Upgrades add-on base image to 11.1.0

---

.github/workflows/deploy.yaml
tasmoadmin/build.yaml
tasmoadmin/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

tasmoadmin/DOCS.md

To make it easier to find and install the add-on.

:books: Add My buttons to documentation

---

tasmoadmin/DOCS.md

Making the My button a bit more easier

:books: Use new My Home Assistant link format

---

tasmoadmin/Dockerfile

Upstream notes: https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta8
should fix #244

⬆️ Upgrades TasmoAdmin to v2.0.0-beta8

---

tasmoadmin/Dockerfile

https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta9
related to #244

⬆️ Upgrades TasmoAdmin to v2.0.0-beta9

---

tasmoadmin/Dockerfile

To be able to build the image this change is required,

⬆️ Upgrades nginx to 1.22.0-r1

---

tasmoadmin/Dockerfile

Since the beta releases were used for some time and some minor bugs ironed out in the later beta releases I felt I should release `v2.0.0`. Changes since `v2.0.0-beta9` was one more release.
Release notes: https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta10
Pending #249 being merged first

⬆️ Upgrades TasmoAdmin to v2.0.0

---

tasmoadmin/Dockerfile
tasmoadmin/build.yaml

Upgrades add-on base image to 12.2.3

⬆️ Upgrades add-on base image to 12.2.3

---

tasmoadmin/Dockerfile

Bump composer to be able to build image. 
N/A

⬆️ Upgrades composer to 2.4.2-r0

---

tasmoadmin/Dockerfile

⬆️ Upgrades nodejs to 16.17.1-r0

---

tasmoadmin/Dockerfile

This dependency is needed for #259 
Should have bumped the version to v3.0.0 in hindsight 
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Add php-dom dependency

---

tasmoadmin/Dockerfile

Upgrades TasmoAdmin to v2.1.1
There was a few important issues fixed here
- Fixes for fallback languages - e.g. for non-english
- Fixes for manual binary uploads (auto path worked fine) 
Changelog https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.1.1
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

⬆️ Upgrades TasmoAdmin to v2.1.1

---

tasmoadmin/Dockerfile

⬆️ Upgrades nginx to 1.22.1-r0

---

tasmoadmin/Dockerfile

⬆️ Upgrades php8 to 8.0.25-r0

---

tasmoadmin/Dockerfile

⬆️ Upgrades git to 2.36.3-r0

---

tasmoadmin/Dockerfile

Adds docker health check, which the Home Assistant Supervisor can leverage to improve its Watchdog functionality.

:stethoscope: Add healthcheck to improve HA watchdog

---

tasmoadmin/Dockerfile

https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.2.0

⬆️ Upgrades TasmoAdmin to v2.2.0

---

tasmoadmin/Dockerfile

🔨 Fix healthcheck for SSL enabled instances
Fixes #273

🔨 Fix healthcheck for SSL enabled instances

---

tasmoadmin/Dockerfile

Required for the container to build.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

⬆️  Upgrades php to 8.1.14

---

tasmoadmin/Dockerfile

https://github.com/TasmoAdmin/TasmoAdmin/compare/v2.2.0...v2.3.2
Main feature is a way to backup from UI
Needs #277 merged first - What's your workflow for testing these changes btw?

⬆️  Upgrades TasmoAdmin to v2.3.3

---

LICENSE.md
README.md
tasmoadmin/.README.j2
tasmoadmin/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

tasmoadmin/Dockerfile
tasmoadmin/build.yaml

⬆️ Upgrades add-on base image to 13.1.0

---

tasmoadmin/Dockerfile

⬆️ Upgrades git to 2.38.3-r1

---

tasmoadmin/Dockerfile
tasmoadmin/build.yaml

⬆️ Upgrades add-on base image to 13.1.3

---

tasmoadmin/Dockerfile

https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.0.1
https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v3.0.0

⬆️ Upgrades TasmoAdmin to v3.0.1

---

.github/dependabot.yaml
.github/renovate.json
tasmoadmin/Dockerfile

Add Renovate for dependency management

---

README.md
tasmoadmin/build.yaml
tasmoadmin/config.yaml

Drop support for armhf & i386

---

LICENSE.md
README.md
tasmoadmin/.README.j2
tasmoadmin/DOCS.md

:fireworks: Updates maintenance/license year to 2024

---

LICENSE.md
README.md
tasmoadmin/.README.j2
tasmoadmin/DOCS.md

:fireworks: Updates maintenance/license year to 2025
